from docx import Document

doc = Document()
doc.add_paragraph("КОММЕРЧЕСКОЕ ПРЕДЛОЖЕНИЕ (техника)")
doc.add_paragraph("№ {{proposal_number}} от {{date}}")
doc.add_paragraph("Клиент: {{client_name}} (ИНН: {{client_inn}})")
doc.add_paragraph("Регион: {{region}}")
doc.add_paragraph("Специализация: {{specialization}}")
doc.add_paragraph()
doc.add_paragraph("На основании предоставленной спецификации и ваших требований предлагаем:")
doc.add_paragraph("{{proposal_text}}")
doc.add_paragraph()
doc.add_paragraph("Экономическое обоснование:")
doc.add_paragraph("- Окупаемость: {{payback}}")
doc.add_paragraph("- Производительность: {{productivity}}")
doc.add_paragraph()
doc.add_paragraph("Итоговая стоимость: {{total_cost}} руб.")
doc.add_paragraph()
doc.add_paragraph("Срок поставки: {{delivery_terms}}")
doc.add_paragraph("Гарантия: {{warranty_terms}}")
doc.add_paragraph()
doc.add_paragraph("С уважением, Команда AI-Ассистентов")

doc.save("data/uploads/template_tech.docx")
print("Шаблон template_tech.docx создан")