services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diler_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/diler_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app_network

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: 8386666876:AAEHa8e-s56KHm7F-RyYs9jLuyDp2-gHawE
      ADMIN_CHAT_ID: 125877403
      API_URL: http://host.docker.internal:8000
      AIOHTTP_DISABLE_IPV6: "1"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: