services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/diler_db
    depends_on:
      - postgres

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: 8386666876:AAEHa8e-s56KHm7F-RyYs9jLuyDp2-gHawE
      ADMIN_CHAT_ID: 125877403
      API_URL: http://backend:8000
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diler_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: